![title](https://i.ibb.co/f2W87Fg/logo2020.png)

---


<table  class="tfo-notebook-buttons" align="left"><tr><td>
    
<a href="https://colab.research.google.com/github/adf-telkomuniv/CV2020_Exercises/blob/main/CV2020 - 00 - Introduction Exercises.ipynb" source="blank" ><img src="https://colab.research.google.com/assets/colab-badge.svg"></a>
</td><td>
<a href="https://github.com/adf-telkomuniv/CV2020_Exercises/blob/main/CV2020 - 00 - Introduction Exercises.ipynb" source="blank" ><img src="https://i.ibb.co/6NxqGSF/pinpng-com-github-logo-png-small.png"></a>
    
</td></tr></table>

# Python NumPy Pre-Exercise 2020
Complete the following tasks according to the expected ouputs

---
### 1. 
**Write your Student ID and Name as string, then print the last four digit of your ID**
    <pre>`(2 lines ★☆☆)`

In [ ]:
ID = '1234567890'
name = 'abcdef'

print('ID           :', ??)
print('Name         :', ??)
print('last 4 digit :', ??)

**Expected Output**:<pre>
<i>(assumed ID='1234567890' and name='abcdef')</i>

ID           : 1234567890
Name         : abcdef
last 4 digit : 7890

---
### 2. 
**Import the numpy package under the name `np`, then print its version**
<pre>(2 lines ★☆☆) 

In [ ]:
import numpy as np
np.??

**Expected Output**:<pre>
'1.1x.x'

---
### 3. 
**Create a null (all-zero) matrix of size $4\ \times\ 5$**
<pre>(1 line ★☆☆)

In [ ]:
A = ??
print(A)

**Expected Output**:<pre>
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


---
### 4. 
**Set the third row values of matrix A to be `all 1`**
<pre>(2 lines ★☆☆)

In [ ]:
??
print(A)

**Expected Output**:<pre>
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]]

---
### 5. 
**Create a random matrix with normal distribution of size $3\ \times\ 4$, using seed value = `123`**
<pre>(2 lines ★☆☆)

In [ ]:
np.??
B = ??
print(B)

**Expected Output**:<pre>
[[-1.0856306   0.99734545  0.2829785  -1.50629471]
 [-0.57860025  1.65143654 -2.42667924 -0.42891263]
 [ 1.26593626 -0.8667404  -0.67888615 -0.09470897]]

---
### 6. 
**print the size of matrix B, then print matrix B with only `2 significant digits`**
<pre>(2 lines ★☆☆)

In [ ]:
np.??
print('size B =', ??)
print(B)

**Expected Output**:<pre>
size B = (3, 4)
[[-1.09  1.    0.28 -1.51]
 [-0.58  1.65 -2.43 -0.43]
 [ 1.27 -0.87 -0.68 -0.09]]


---
### 7
**create a vector with values raging from `15 to 35`**
<pre>(1 line ★☆☆)

In [ ]:
C = ??
print(C)

**Expected Output**:
<pre>[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]

---
### 8.  
**Reverse vector C (first element becomes last)**<pre> (1 line ★☆☆) 

In [ ]:
D = ??
print(C)
print(D)

**Expected Output**:<pre>
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]
[35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15]



---
### 9. 
**Create a $4\ \times\ 3$ matrix with values ranging from 0 to 11**<pre> (1 line ★☆☆) 


In [ ]:
E = ??
print(E)

**Expected Output**:<pre>
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

---
### 10. 
**Find the indices of non-zero elements from the given matrix**<pre> (1 line ★☆☆) 

In [ ]:
F = [1,2,0,0,4,0,0,7]
idF = ??
print(idF[0])

**Expected Output**:<pre>[0 1 4 7]

---
### 11.
**Create a $4\ \times\ 4$ identity matrix**<pre> (1 line ★☆☆) 

In [ ]:
G = ??
print(G)

**Expected Output**:<pre>[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

---
### 12. 
**Create a $3\ \times\ 2\ \times\ 3$ array of random values with uniform distribution and seed value = 123**<pre> (2 lines ★☆☆) 

In [ ]:
np.??
H = ??
print(H)

**Expected Output**:
<pre>
[[[0.7  0.29 0.23]
  [0.55 0.72 0.42]]

 [[0.98 0.68 0.48]
  [0.39 0.34 0.73]]

 [[0.44 0.06 0.4 ]
  [0.74 0.18 0.18]]]

---
### 13.
**Find the minimum and maximum values of matrix (H)**<pre> (2 lines ★☆☆) 

In [ ]:
Hmin = ??
Hmax = ??
print(Hmin, Hmax)

**Expected Output**:<pre>0.05967789660956835 0.9807641983846155


---
### 14. 
**Create a random vector of size 50 and find the mean value**<pre> (2 lines ★☆☆) 

In [ ]:
np.random.seed(123)
I = ??
mI = ??
print(mI)

**Expected Output**:<pre>0.5018578670875471



---
### 15. 
**Create a $5 \times 5 $ array with all values = 1** <pre>(1 line ★☆☆) 

In [ ]:
J = ??
print(J)

**Expected Output**:<pre>[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

---
### 16. 
**Set matrix J so that the value in `3rd to 4th` row, from `2nd to 4th` column, are all 0** <pre>(1 line ★☆☆) 

In [ ]:
??
print(J)

**Expected Output**:<pre>
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

---
### 17. 
**Create a $4\ \times\ 4$ Random Integer matrix in range `[0..9]`, then add a zero padding border (filled with 0's) around it**<pre> (2 lines ★★☆) 

In [ ]:
np.random.seed(12)
K = ??
K = ??
print(K)

**Expected Output**:<pre>
[[0 0 0 0 0 0]
 [0 6 1 2 3 0]
 [0 3 0 6 1 0]
 [0 4 5 2 6 0]
 [0 0 5 8 2 0]
 [0 0 0 0 0 0]]


---
### 18. 
**Create a $6\ \times\ 6$ matrix with values `0,1,2,3,4,5` on the diagonal** <pre>(1 line ★☆☆) 

In [ ]:
L = ??
print(L)

**Expected Output**:<pre>[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]


---
### 19. 
**Create a $7\ \times\ 7$ matrix with values `1,2,3,4,5,6` just `BELOW` the diagonal** <pre>(1 line ★☆☆) 

In [ ]:
M = ??
print(M)

**Expected Output**:<pre>[[0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 6 0]]


---
### 20. 
**Create a $6\ \times\ 6$ matrix and fill it with a checkerboard pattern `WITHOUT` helper function** <pre>(3 lines ★★☆) 

In [ ]:
N = ??  # use dtype=int
??
??
print(N)

**Expected Output**:<pre>[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


---
### 21. 
**Create a checkerboard $6\ \times\ 6$ matrix using the `tile` function**<pre> (1 line ★☆☆)

In [ ]:
O = ??
print(O)

**Expected Output**:<pre>[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


---
### 22. 
<strike>**Create a 3 x 4 random uniform matrix, then normalize the values to range [0-1]**</strike> <font color="red">[updated 11-09-20]</font><br>
**Create a $3\ \times\ 2$ random uniform matrix, then normalize the values to range [0-1]**<pre> (2 lines ★★☆) 



In [ ]:
np.random.seed(25)
P = ??
print('before')
print(P,'\n')

Pmax, Pmin = P.max(), P.min()
P = ??
print('after')
print(P)

**Expected Output**:<pre>before
[[0.87 0.58]
 [0.28 0.19]
 [0.41 0.12]] 
<br>after
[[1.   0.62]
 [0.21 0.09]
 [0.39 0.  ]]



---
### 23. 
**Multiply matrix `E` by matrix `P` (dot product)**<pre> (1 line ★☆☆)

In [ ]:
Q = ??
print(Q)

**Expected Output**:<pre>[[ 0.99  0.09]
 [ 5.81  2.22]
 [10.62  4.34]
 [15.44  6.47]]


---
### 24. 
**Given a 1D array, negate all elements which are `between -4 and 4`, in place.** 
<br>(switch positive/negative sign)<pre> (1 line ★☆☆)

In [ ]:
R = np.arange(-8,9)
print('before')
print(R,'\n')

??
print('after')
print(R)

**Expected Output**:
<pre>before
[-8 -7 -6 -5 -4 -3 -2 -1  0  1  2  3  4  5  6  7  8] 
<br>after
<strike>[-8 -7 -6 -5 -4  3  2  1  0 -1 -2  3  4  5  6  7  8]</strike><font color="red"> [updated 11-09-20]</font>
[-8 -7 -6 -5 -4  3  2  1  0 -1 -2 -3  4  5  6  7  8]


---
### 25. 
**Get common values between two given arrays**<br>
(number appears in both arrays)<pre> (1 line ★☆☆) 

In [ ]:
np.random.seed(3)
S1 = np.random.randint(0,10,10)
print('S1=', S1,'\n')

np.random.seed(5)
S2 = np.random.randint(0,10,10)
print('S2=', S2,'\n')

S = ??
print('S =', S)

**Expected Output**:<pre>S1= [8 9 3 8 8 0 5 3 9 9] 
<br>S2= [3 6 6 0 9 8 4 7 0 0] 
<br>S = [0 3 8 9]


---
### 26 
**Create random uniform vector of `size 12` then replace the maximum value by `1`, and replace the minimum value by `0`**<pre>( 3 lines ★★☆) 

In [ ]:
np.random.seed(15)
T = ??
print('before=',T,'\n')

??
??
print('after =',T)

**Expected Output**:<pre>before= [0.85 0.18 0.05 0.36 0.28 0.53 0.31 0.3  0.11 0.25 0.92 0.26] 
<br>after = [0.85 0.18 0.   0.36 0.28 0.53 0.31 0.3  0.11 0.25 1.   0.26]

---
### 27. 
**Get the `MEAN` of matrix `Q`, also `mean value across the row and column`**<pre> (2 line ★★☆)</pre>
hint: use `axis ` and `keepdims`

In [ ]:
print('Q')
print(Q,'\n')
U1 = ??
U2 = ??
U3 = ??

print('Matrix Mean')
print(U1,'\n')

print('Row Mean')
print(U2,'\n')

print('Column Mean')
print(U3)

**Expected Output**:<pre>Q
[[ 0.99  0.09]
 [ 5.81  2.22]
 [10.62  4.34]
 [15.44  6.47]] 
<br>Matrix Mean
5.748021117169012 
<br>Row Mean
[[ 0.54]
 [ 4.01]
 [ 7.48]
 [10.95]] 
<br>Column Mean
[[8.22 3.28]]

---
### 28. 
**Swap 1st and 3rd row of given $5\ \times\ 5$ matrix**<pre>(1 line ★★☆) 

In [ ]:
np.random.seed(21)
V = np.random.randint(1,10,(5,5))
print('before')
print(V,'\n')

??
print('after')
print(V)

**Expected Output**:<pre>before
[[9 5 1 1 9]
 [4 3 2 9 7]
 [1 5 7 5 5]
 [8 9 6 7 6]
 [3 7 3 9 3]] 
<br>after
[[1 5 7 5 5]
 [4 3 2 9 7]
 [9 5 1 1 9]
 [8 9 6 7 6]
 [3 7 3 9 3]]

---
### 29. 
**Reshape a given $4\ \times\ 6$ matrix into a $2\ \times\ 12$ matrix**<pre>(1 line ★☆☆) 

In [ ]:
W = np.random.randint(1,10,(4,6))
print('before')
print(W)
print('shape: ', W.shape,'\n')

??
print('after')
print(W)
print('shape: ', W.shape,'\n')


**Expected Output**:<pre>
before
[[2 1 9 4 5 1]
 [3 1 9 2 2 5]
 [7 9 6 1 4 6]
 [8 1 9 6 4 8]]
shape:  (4, 6) 
<br>after
[[2 1 9 4 5 1 3 1 9 2 2 5]
 [7 9 6 1 4 6 8 1 9 6 4 8]]
shape:  (2, 12) 

---
### 30. 
**Reshape previous matrix into a $2\ \times\ 3\times\ 4$ matrix** <br>
(3 dimensional)<pre>(1 line ★☆☆) 

In [ ]:
??
print('after')
print(W)
print('shape: ', W.shape,'\n')


**Expected Output**:<pre>after
[[[2 1 9 4]
  [5 1 3 1]
  [9 2 2 5]]
<br> [[7 9 6 1]
  [4 6 8 1]
  [9 6 4 8]]]
shape:  (2, 3, 4) 

---
### 31. 
**Reshape previous matrix into a 1 dimensional array** <br>
(flatten)<pre>(1 line ★☆☆) 

In [ ]:
??
print('after')
print(W)
print('shape: ', W.shape,'\n')


**Expected Output**:<pre>after
[2 1 9 4 5 1 3 1 9 2 2 5 7 9 6 1 4 6 8 1 9 6 4 8]
shape:  (24,)

---
### i. 
**Save all matrices `A to V` into a `.npz` file with your ID as the filename**

In [ ]:
np.savez(ID+'.npz', A=A, B=B, C=C, D=D, E=E, F=F, G=G, H=H, I=I, J=J, K=K, L=L, M=M, N=N, O=O, P=P, Q=Q, R=R, S=S, T=T, U1=U1, U2=U2, U3=U3, V=V)

In [ ]:
print(data['A'].shape)
print(data['Q'].shape)
print(data['V'].shape)

---
### ii.
**Clear all variables using `%reset`, then load your `.npz` file into `data` dictionary and verify the loaded matrices**

run this and press y to reset all variables

In [ ]:
%reset

check loaded variables

In [ ]:
import numpy as np
ID = '1234567890'
data = np.load(ID+'.npz')
print(data['A'].shape)
print(data['Q'].shape)
print(data['V'].shape)

---

# Congratulation, You've Completed Pre-Exercise
<p>Copyright &copy;  <a href=https://www.linkedin.com/in/andityaarifianto/>2020 - ADF</a> </p>

![footer](https://i.ibb.co/yX0jfMS/footer2020.png)